# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9845c1017bb627e45a2f23516ab1dd3e9fdd520c561c79b3515814c6c15a9cc251245eef10f5cac785499885f6e50c54abbcb1204c1f7ea2319492b62f65e2a

test:
  secret_key_base: e4c29dc25c0332afc84e0051ee67122057e2c6e68e129d082f675391a778491ebb8fb9067cf8a2263c38460d2e68a8b32785a8d0c1234cea94dac2cc73ac7419

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
